import type { Metadata } from 'next'
import Image from 'next/image'
import Link from 'next/link'
import { Roboto_Condensed } from 'next/font/google'
import './globals.css'
import { ReactNode } from 'react'

const roboto = Roboto_Condensed({ subsets: ['latin', 'cyrillic'] })

export const metadata: Metadata = {
  title: 'My test App',
  description: 'Generated by create next app, edited by me',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <header className="fixed top-0 flex w-full gap-2 bg-white p-2 align-middle">
          <Image src="/next.svg" alt="Next.js Logo" width={180} height={37} />
          <nav className="ml-auto flex gap-2 align-middle">
            <Link href="">Главная</Link>
            <Link href="">Кабинет</Link>
          </nav>
        </header>
        <main className="h-container flex flex-col justify-between p-2">
          {children}
        </main>
      </body>
    </html>
  )
}
